### ISSUE TITLE
Aussenstellen abgeschnitten

### ISSUE THREAD

**Issue by eest9** [Metalab/library-opac#21]
Hi,
bei kleineren Bildschirmauflösungen sind die Aussenstellen und die Suche abgeschnitten.
![Bildschirmfoto von 2020-11-08 18-52-27](https://user-images.githubusercontent.com/11019106/98484586-f890ea80-2210-11eb-8922-24400224b19e.png)

**Comment by deadda7a** [comment]
Fixed.
