### ISSUE TITLE
Footer will Bücher verbergen

### ISSUE THREAD

**Issue by eest9** [Metalab/library-opac#31]
Der Footer verdeckt wenn man ganz nach unten scroolt das letzte Buch fast bis zur Hälfte. Die ISBN ist so nur schwer lesbar.
![Bildschirmfoto von 2020-11-16 14-40-48](https://user-images.githubusercontent.com/11019106/99259225-fa167000-2819-11eb-81b8-97fb638aa14a.png)

**Comment by deadda7a** [comment]
Ich weiß, das hab ich in meinem i18n Branch schon gefixt, aber der ist 
noch nicht gemerged
