### ISSUE TITLE
image ratio wrong on small viewports

### ISSUE THREAD

**Issue by nunner** [Metalab/library-opac#7]
When viewing the website in a smaller window, the image ratios are all messed up. Weirdly, the leftmost logo doesn't seem to be affected. 

![image](https://user-images.githubusercontent.com/40544875/97491323-46c90280-1962-11eb-9a82-fe51ce569820.png)

**Comment by eest9** [comment]
Thanks for your contribution!
We (aka @deadda7a) will look into it!

**Comment by joak** [comment]
e04762a8419e32ba7d087e6f6b535717768e3b40 Done! :smile: 
@deadda7a  I checked it in firefox and chromium, I think it should work
